name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    # Runs a single command using the runners shell
    - name: Install node modules
      run: npm install
  
      # Runs a single command using the runners shell
    - name: Build website
      run: npm run build

    - name: Deploy to Azure static website
      uses: tibor19/static-website-deploy@v1
      with:
        # Connection String of the Azure Storage Container
        connection-string: ${{ secrets.AzureBlobStorageConnectionString }}
        # Folder containing the files to be uploaded to the Storage Container
        folder: dist # optional, default is .
        # Name of the Blob Container Storage
        blob-container-name: $web # optional
        # If the existing files should be removed before uploading the new files
        remove-existing-files: true # optional
#         # Access Policy to update in the Container (BlobContainer | Blob | None). For private containers do not specity any value.
#         public-access-policy: # optional
#         # Enabled static website
#         enabled-static-website: # optional
#         # Index file for the static website
#         index-file: # optional
#         # 404 Error file for the static website
#         error-file: # optional
